# Generated by Django 3.0.7 on 2022-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='choice',
        ),
        migrations.AddField(
            model_name='user_details',
            name='User_Type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
