# Generated by Django 3.0.7 on 2022-03-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='draft',
            new_name='Publish',
        ),
    ]
